### ISSUE TITLE
What's the status of this module?

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/field_collection#17]
Porting this module has begun in 2021, but seems stalled.
Several severe bugs (open issues) haven't had any activity in a while.

I'm aware, this module's a monster to port, but is there any plan to finalize it, anyway, or is this more like an abandoned project?

I think, a statement, which crucial parts are broken, which ones work, and what to expect re development here, might help people to decide, whether it makes sense to contribute. :wink: Or even to consider this module or to seek for alternatives.

**Comment by stpaultim** [comment]
I think it's worth noting the at the time it was ported, the maintainer appears to have been unaware of these severe bugs. 

https://github.com/backdrop-ops/contrib/issues/590

I see several issues have been opened since then. @oadaeh is there any chance you are still interested in this module?

Is anyone else interested in working on it? Maybe someone that has looked at it since the original port is in a better position to report on how big the problems are and how much work they might take to fix.

**Comment by stpaultim** [comment]
It seems that some others have chosen to upgrade field collections into Paragraphs. For more information on that:
https://github.com/backdrop-contrib/paragraphs/issues/53

**Comment by oadaeh** [comment]
As far as I know, there is actually only one severe bug, #14. #13 was probably a problem in my test environment, and the OP has never responded back on #6 with more information. Other than that, the module is working for me in my tests and uses.
