### ISSUE TITLE
Error: Call to undefined function entity_save()

### ISSUE THREAD

**Issue by sanjeevrehan01** [backdrop-contrib/field_collection#4]
I was Testing this module and getting Error: Call to undefined function entity_save() in FieldCollectionItemEntity->save() in (line 505 of field_collection\field_collection.entity.inc ) when trying to save field collection form 
Entity Plus modules also installed

**Comment by oadaeh** [comment]
Thanks for reporting this.
I'm assuming that you were using the Add link when viewing the entity. I hadn't tried that link before, so I didn't see the error.

**Comment by oadaeh** [comment]
I have fixed this problem with [this commit](https://github.com/backdrop-contrib/field_collection/commit/e09ce2474f823a5ee6fdd49142d5b043bebcba9e).
There is still some weirdness in that the caches need to be cleared in order to see the new field collection, but other than that, it seems to be working correctly.
